server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# ???????
spring:
  profiles:
    active: dev
  # JPA??
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
rocketmq:
  producer:
    group: your_producer_group # 生产者组名
  consumer:
    group: your_consumer_group # 消费者组名
    topic: your_topic # 订阅的主题
    tag: your_tag # 订阅的标签
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
