spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chatters
    username: root
    password: example
  redis:
    port: 6379
    host: 127.0.0.1
    password:
mq:
  nameServer: 127.0.0.1:9876
  topicNumber: 1
rocketmq:
  name-server: 127.0.0.1:9876 # RocketMQ nameserver地址
  producer:
    group: your_producer_group # 生产者组名
  consumer:
    group: your_consumer_group # 消费者组名
    topic: your_topic # 订阅的主题
    tag: your_tag # 订阅的标签
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
logging.level.org.springframework.security: DEBUG
logging.level.org.springframework.web.socket: DEBUG